language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - cd example
  - pip install -r requirements.txt

# command to run tests
script:
   coverage run --omit */site-packages/*,*/migrations/*,*/lib/* manage.py test app.tests --settings=dj.settings.settings -v 2
